### ISSUE TITLE
Socket gaierror with default simultaneous requests

### ISSUE THREAD

**Issue by MartinHjelmare** [topic2k/pygcgen#23]
**Description:**
When running with the hardcoded `MAX_SIMULTANEOUS_REQUESTS` set to 25, in `fetcher.py`, I get one error and traceback when one of the worker makes a connection. See below for traceback. So one run generates one traceback.

I've tried setting `MAX_SIMULTANEOUS_REQUESTS` to 1, which avoids the error. Setting it to 10 also avoids the error. I haven't investigated further.

If this setting is sensitive to different users, it would be cool to have a command line option to easily change it. But maybe it's enough to lower it somewhat? Or maybe there's a totally different approach and solution to this problem?

Thanks for this package! It's saved me a bunch of work.

**pygcgen version:**
`pygcgen v0.2.2`

**Tested Python versions:**
Python 3.5.4
Python 3.6.5

**Tested command:**
```
pygcgen -u OWNER -p REPO --section "**Breaking Changes:**" "breaking change" --with-unreleased --future-release 0.13.0 -v
```

**Traceback:**
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/martin/.virtualenvs/p3.6/lib/python3.6/site-packages/pygcgen/fetcher.py", line 260, in worker
    page=page, per_page=PER_PAGE_NUMBER)
  File "/home/martin/.virtualenvs/p3.6/lib/python3.6/site-packages/agithub/base.py", line 157, in get
    return self.request('GET', url, None, headers)
  File "/home/martin/.virtualenvs/p3.6/lib/python3.6/site-packages/agithub/base.py", line 207, in request
    conn.request(method, url, requestBody.process(), headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by topic2k** [comment]
Hmm, strange. Looks like the repo-server (github.com?) couldn't be reached.

I'm trying to reproduce the error, but with no luck. Is the repo public?

**Comment by MartinHjelmare** [comment]
Yep, it's this one:
https://github.com/theolind/pymysensors

**Comment by topic2k** [comment]
The only way for me to get a similar exception was to disconnect my ethernet-cable or deactivate the network-adapter.

I see the repo has now a [changelog](https://github.com/theolind/pymysensors/releases/tag/0.13) for 0.13. Does it mean the error is gone or is it still reproducable on your system?

**Comment by MartinHjelmare** [comment]
It's still reproducible if I change `MAX_SIMULTANEOUS_REQUESTS` back to 25.

**Comment by topic2k** [comment]
Version 0.2.3 adds an option to set the `--max-simultaneous-requests` and i lowered the default value to 10.

**Comment by MartinHjelmare** [comment]
Thanks!
